apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: development
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/development/namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system